name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
      - production
  pull_request:
    branches:
      - main
      - development
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 --tag vansh321/my-nodejs-app:latest --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref == 'refs/heads/production'

    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to Production Server"
        ssh user@your-server-ip "docker pull vansh321/my-nodejs-app:latest && docker run -d -p 3000:3000 vansh321/my-nodejs-app:latest"
